### ISSUE TITLE
Some issues with example

### ISSUE THREAD

**Issue by kevinruby** [RodrigoEspinosa/mongoose-orchestrator#1]
Hi,

When I install this module via npm, the example doesn't work.
First `const mongooseOrchestrator = require('../src/index');` doesn't work, the "src" folder do not exist, so it must be `const mongooseOrchestrator = require('../lib/index');`.
After fix, I get the following error `Error: Cannot find module 'babel-polyfill'`, so we need to make npm install babel-polyfill and the example work fine.

**Comment by RodrigoEspinosa** [comment]
Hi! First of all, thanks for opening this issue! First issue, awesome!

The example project is something I made to work inside this repository and I see that made some confusion. 

This make me realize, I really need to improve the documentation.

When using this plugin in your own project, you will first install it using `npm install mongoose-orchestrator --save` and then, require it as the following:

``` js
var mongooseOrchestrator = require('mongoose-orchestrator');
```

Please tell me if the Babel Pollyfill error persist after this change. I will try to update the documentation (and probably remove the example dir) in the next few days. 

Thanks!

rec.

**Comment by kevinruby** [comment]
The Babel Pollyfill error persist after this change.

Thnaks for the fast reply.

**Comment by RodrigoEspinosa** [comment]
Interesting. What's your Node version?

I try keep this tested on Node **v4.0** and **v.0.12**, [latest Travis build](https://travis-ci.org/RodrigoEspinosa/mongoose-orchestrator/jobs/111114902).

**Comment by kevinruby** [comment]
Node v4.3.1 on Windows 10.

**Comment by RodrigoEspinosa** [comment]
Well, that _should_ work. Can you paste here how are you using the plugin? Thanks :smiley:!
